### ISSUE TITLE
Práctica Contrato_METZTLI

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/actividad-10-desarrollo-de-un-contrato-entrevista-metztli_team#1]
[Práctica Contrato METZTL.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-desarrollo-de-un-contrato-entrevista-metztli_team/files/10192514/Practica.Contrato.METZTL.pdf)

**Comment by carlos-chrs** [comment]
Calificado. Buen trabajo 50/50

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
